controller_list:
  - name: fake_kuka_iiwa_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7
initial:  # Define initial robot poses per group
  - group: kuka_iiwa_arm
    pose: look_down_pose